version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - npm install
      - npm install -g @angular/cli
  pre_build:
    commands:
      - echo "pre build phase"
  build:
    commands:
      - npm run build --prod
  post_build:
    commands:
      - echo "post build phase"
artifacts:
  files:
    - "**/*"
    discard-paths: no
    base-directory: dist/wadvisor
