version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - "echo \"installation phase\""
  pre_build:
    commands:
      - "echo \"pre build phase\""
      - "npm install"
      - "npm install -g @angular/cli"
  build:
    commands:
      - "echo \"build phase\""
      - "ng build --prod"
  post_build:
    commands:
      - "echo \"post build phase\""
