version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - "sudo npm install -n"
      - "npm install -g @angular/cli"
  pre_build:
    commands:
      - "echo \"pre build phase\""
  build:
    commands:
      - "ng build --prod"
  post_build:
    commands:
      - "echo \"post build phase\""
